[package]
<<<<<<< HEAD
name = "cosmian_memories"
=======
name = "cosmian_findex_memories"
>>>>>>> ba65f62 (feat: start the new branch)
version.workspace = true
authors.workspace = true
license.workspace = true
edition.workspace = true
categories.workspace = true
keywords.workspace = true
repository.workspace = true
description.workspace = true
readme = "README.md"

[lib]
name = "cosmian_memories"
path = "src/lib.rs"

[features]
redis-mem = ["redis"]
sqlite-mem = ["async-sqlite"]
postgres-mem = ["deadpool-postgres", "tokio", "tokio-postgres"]
test-utils = ["tokio"]

[dependencies]
async-sqlite = { version = "0.5", optional = true }
cosmian_crypto_core.workspace = true
deadpool-postgres = { version = "0.14", optional = true }
redis = { version = "0.32", default-features = false, features = [
    "connection-manager",
    "tokio-comp",
], optional = true }
tokio = { workspace = true, optional = true }
tokio-postgres = { version = "0.7", optional = true, features = [
    "array-impls",
] }

[dev-dependencies]
<<<<<<< HEAD
cosmian_crypto_core.workspace = true
tokio = { workspace = true, features = ["macros", "rt-multi-thread"] }
=======
cosmian_findex = { path = "../findex", version = "8.0", features = [
    "test-utils",
] }
futures = { version = "0.3" } # TODO delete ?
tokio = { workspace = true, features = [
    "macros",
    "rt-multi-thread",
] } # TODO delete ?
criterion = { workspace = true }
rand = { version = "0.9.0" }
rand_distr = { version = "0.5.1" }

[[bench]]
name = "benches"
harness = false
required-features = ["redis-mem", "sqlite-mem", "postgres-mem", "test-utils"]

[[example]]
name = "redis"
required-features = ["redis-mem"]

[[example]]
name = "sqlite"
required-features = ["sqlite-mem"]

[[example]]
name = "postgresql"
required-features = ["postgres-mem"]
>>>>>>> ba65f62 (feat: start the new branch)
