[package]
name = "cosmian_findex_memories"
version.workspace = true
authors.workspace = true
license.workspace = true
edition.workspace = true
categories.workspace = true
keywords.workspace = true
repository.workspace = true
description.workspace = true
readme.workspace = true

[lib]
name = "cosmian_findex_memories"
path = "src/lib.rs"

[features]
redis-mem = ["redis"]
sqlite-mem = ["async-sqlite"]
postgres-mem = ["tokio-postgres", "tokio", "deadpool-postgres"]
test-utils = ["cosmian_findex/test-utils"]

[dependencies]
cosmian_crypto_core.workspace = true
cosmian_findex = { path = "../findex" }
async-sqlite = { version = "0.4", optional = true } # `async-sqlite` dependency is pinned at v0.4 due to dependency tree issues with sqlx requiring a lower version of `libsqlite3-sys`
deadpool-postgres = { version = "0.14.1", optional = true }
redis = { version = "0.31", features = [
    "aio",
    "connection-manager",
    "tokio-comp",
], optional = true }
tokio = { workspace = true, features = ["rt-multi-thread"], optional = true }
tokio-postgres = { version = "0.7.9", optional = true, features = [
    "array-impls",
] }

[dev-dependencies]
cosmian_findex = { path = "../findex", features = ["test-utils"] }
futures = { version = "0.3" }
tokio = { workspace = true, features = ["macros", "rt-multi-thread"] }
criterion = { workspace = true }
rand = { workspace = true }
rand_distr = { workspace = true }

[[bench]]
name = "benches"
harness = false
required-features = ["redis-mem", "sqlite-mem", "postgres-mem", "test-utils"]

[[example]]
name = "redis"
required-features = ["redis-mem"]

[[example]]
name = "sqlite"
required-features = ["sqlite-mem"]

[[example]]
name = "postgresql"
required-features = ["postgres-mem"]
