[package]
name = "cosmian_findex"
version = "7.0.0"
authors = [
    "Bruno Grieder <bruno.grieder@cosmian.com>",
    "Célia Corsin <celia.corsin@cosmian.com>",
    "Chloé Hébant <chloe.hebant@cosmian.com>",
    "Emmanuel Coste <emmanuel.coste@cosmian.com>",
    "Hatem Mnaouer <hatem.mnaouer@cosmian.com>",
    "Théophile Brézot <theophile.brezot@cosmian.com>",
]
categories = ["cryptography"]
edition = "2021"
keywords = ["SSE"]
license = "BUSL-1.1"
repository = "https://github.com/Cosmian/findex/"
description = "Symmetric Searchable Encryption"

[lib]
name = "cosmian_findex"
path = "src/lib.rs"

[features]
rust-mem = []
redis-mem = ["redis"]
sqlite-mem = ["async-sqlite"]
test-utils = ["tokio", "criterion", "futures", "rand"]

[dependencies]
aes = "0.8"
cosmian_crypto_core = { version = "10.1", default-features = false, features = ["macro", "sha3"] }
xts-mode = "0.5"

# Used in benches and tests.
futures = { version = "0.3", optional = true }
criterion = { version = "0.5", optional = true }
rand = { version = "0.9.0", optional = true }
rand_distr = { version = "0.5.1", optional = true }
tokio = { version = "1.44", features = ["rt", "rt-multi-thread"], optional = true }

# Memory dependencies
async-sqlite = { version = "0.5", optional = true }
redis = { version = "0.28", features = [
    "aio",
    "connection-manager",
    "tokio-comp",
], optional = true }
tokio = { version = "1.44", features = ["rt-multi-thread"], optional = true }


[dev-dependencies]
futures = "0.3"
tokio = { version = "1.44", features = [
    "macros",
    "rt",
    "rt-multi-thread",
    "time",
] }

[[bench]]
name = "benches"
harness = false
required-features = ["test-utils"]

[[example]]
name = "insert"
required-features = ["test-utils"]
