[package]
name = "cosmian_findex"
version = "2.0.1"
authors = [
  "Chloé Hébant <chloe.hebant@cosmian.com>",
  "Bruno Grieder <bruno.grieder@cosmian.com>",
  "Célia Corsin <celia.corsin@cosmian.com>",
  "Emmanuel Coste <emmanuel.coste@cosmian.com>",
]
categories = ["cosmian::crypto"]
edition = "2021"
keywords = ["SSE"]
license = "MIT/Apache-2.0"
repository = "https://github.com/Cosmian/findex/"
description = "Symmetric Searchable Encryption"

[lib]
crate-type = ["cdylib", "rlib", "staticlib"]
name = "cosmian_findex"
path = "src/lib.rs"

[features]
ffi = ["interfaces", "interfaces", "serde", "serde_json", "cosmian_ffi"]
sqlite = ["rusqlite", "faker_rand", "interfaces", "serde", "serde_json"]
wasm_bindgen = ["interfaces", "js-sys", "wasm-bindgen", "wasm-bindgen-test", "web-sys", "wasm-bindgen-futures", "interfaces"]
interfaces = []
python = ["interfaces", "pyo3"]

[dependencies]
async-recursion = "1.0.0"
base64 = "0.13"
cosmian_crypto_core = "6.0"
cosmian_ffi = { version = "1.0.0", optional = true }
faker_rand = { version = "0.1", optional = true }
futures = { version = "0.3" }
hex = "0.4"
js-sys = { version = "0.3", optional = true }
leb128 = "0.2"
pyo3 = { version = "0.17", features = ["extension-module", "abi3", "abi3-py37", "generate-import-lib"], optional = true }
rand = "0.8"
rusqlite = { version = "0.28", features = ["bundled"], optional = true }
serde = { version = "1.0", features = ["derive"], optional = true }
serde_json = { version = "1.0", optional = true }
sha3 = "0.10"
thiserror = "1"
tiny-keccak = { version = "2.0.2", features = ["kmac"] }
wasm-bindgen = { version = "0.2", features = ["serde-serialize"], optional = true }
wasm-bindgen-futures = { version = "0.4", optional = true }
wasm-bindgen-test = { version = "0.3", optional = true }
web-sys = { version = "0.3", features = ['Document', 'Element', 'HtmlElement', 'Node', 'Window'], optional = true }
zeroize = "1.5"

[dev-dependencies]
actix-rt = "2"
criterion = { version = "0.4", features = ["html_reports", "async_futures"], default_features = false }

[[bench]]
harness = false
name = "benches"

[profile.bench]
debug = true
