[package]
name = "cosmian_findex"
version = "7.0.0"
authors = [
    "Bruno Grieder <bruno.grieder@cosmian.com>",
    "Célia Corsin <celia.corsin@cosmian.com>",
    "Chloé Hébant <chloe.hebant@cosmian.com>",
    "Emmanuel Coste <emmanuel.coste@cosmian.com>",
    "Hatem Mnaouer <hatem.mnaouer@cosmian.com>",
    "Théophile Brézot <theophile.brezot@cosmian.com>",
]
categories = ["cryptography"]
edition = "2021"
keywords = ["SSE"]
license = "BUSL-1.1"
repository = "https://github.com/Cosmian/findex/"
description = "Symmetric Searchable Encryption"

[lib]
name = "cosmian_findex"
path = "src/lib.rs"

[features]
redis-mem = ["redis"]
sqlite-mem = ["async-sqlite"]
test-utils = ["tokio"]

[dependencies]
aes = "0.8.4"
cosmian_crypto_core = { git = "https://github.com/Cosmian/crypto_core.git", branch = "develop", default-features = false, features = ["sha3"] }
xts-mode = "0.5.1"

# Memory dependencies
async-sqlite = { version = "0.5.0", optional = true }
redis = { version = "0.28.2", features = [
    "aio",
    "connection-manager",
    "tokio-comp",
], optional = true }
tokio = { version = "1.44.0", features = ["rt-multi-thread"], optional = true }

[dev-dependencies]
cosmian_crypto_core = { git = "https://github.com/Cosmian/crypto_core.git", branch = "develop", default-features = false, features = ["macro"] }
criterion = "0.5.1"
futures = "0.3.31"
lazy_static = "1.5.0"
tokio = { version = "1.43.0", features = [
    "macros",
    "rt",
    "rt-multi-thread",
    "time",
] }

[[bench]]
name = "benches"
harness = false
required-features = ["test-utils"]

[[example]]
name = "insert"
required-features = ["test-utils"]
