[workspace]
default-members = ["crate/findex"]
members = ["crate/findex", "crate/memories"]
resolver = "2"

[workspace.package]
version = "7.1.0"
authors = [
    "Bruno Grieder <bruno.grieder@cosmian.com>",
    "Célia Corsin <celia.corsin@cosmian.com>",
    "Chloé Hébant <chloe.hebant@cosmian.com>",
    "Emmanuel Coste <emmanuel.coste@cosmian.com>",
    "Hatem Mnaouer <hatem.mnaouer@cosmian.com>",
    "Théophile Brézot <theophile.brezot@cosmian.com>",
]
categories = ["cryptography"]
edition = "2021"
keywords = ["SSE"]
license = "BUSL-1.1"
repository = "https://github.com/Cosmian/findex/"
description = "Symmetric Searchable Encryption"


[workspace.dependencies]
cosmian_crypto_core = { version = "10.1", default-features = false, features = [
    "macro",
    "sha3",
] }
criterion = { version = "0.6" }
rand = { version = "0.9.0" }
rand_distr = { version = "0.5.1" }
tokio = { version = "1.44" }


# TODO: later
# [[bench]]
# name = "benches"
# harness = false
# required-features = ["test-utils"]

# [[example]]
# name = "insert"
# required-features = ["test-utils"]
