[package]
name = "findex"
version = "0.1.0"
edition = "2021"

[features]
bench = []

[dependencies]
aes = "0.8.4"
cosmian_crypto_core = {version = "9.5", default-features = false, features = ["aes", "sha3"]}
xts-mode = "0.5.1"

[dev-dependencies]
futures = "0.3.30"
criterion = "0.5.1"
tokio = {version = "1.38.0", features = ["rt", "macros", "rt-multi-thread", "time"]}
lazy_static = "1.5.0"

[[bench]]
name = "benches"
harness = false
required-features = ["bench"]

[[example]]
name = "insert"
required-features = ["bench"]
