[package]
name = "cosmian_findex"
version = "3.0.0"
authors = [
  "Chloé Hébant <chloe.hebant@cosmian.com>",
  "Bruno Grieder <bruno.grieder@cosmian.com>",
  "Célia Corsin <celia.corsin@cosmian.com>",
  "Emmanuel Coste <emmanuel.coste@cosmian.com>",
]
categories = ["cosmian::crypto"]
edition = "2021"
keywords = ["SSE"]
license = "MIT/Apache-2.0"
repository = "https://github.com/Cosmian/findex/"
description = "Symmetric Searchable Encryption"

[lib]
crate-type = ["cdylib", "rlib", "staticlib"]
name = "cosmian_findex"
path = "src/lib.rs"

[features]
interfaces = []

[dependencies]
async-recursion = "1.0.0"
base64 = "0.13"
cosmian_crypto_core = "6.0"
futures = { version = "0.3" }
hex = "0.4"
leb128 = "0.2"
rand = "0.8"
sha3 = "0.10"
thiserror = "1"
tiny-keccak = { version = "2.0.2", features = ["kmac"] }
zeroize = "1.5"
