[package]
name = "findex"
version = "0.1.0"
edition = "2021"

[features]
bench = []
cloudproof = ["futures", "tokio", "redis"]

[dependencies]
aes = "0.8.4"
rand = "0.8.5"
rand_chacha = "0.3.1"
rand_core = "0.6.4"
redis = {version = "0.27.5", optional = true}
tiny-keccak = { version = "2.0.2", features = ["sha3"] }
xts-mode = "0.5.1"
zeroize = { version = "1.8.1", features = ["derive"] }
futures = {version = "0.3.30", optional = true}
tokio = {version = "1.38.0", optional = true, features = ["rt"]}

[dev-dependencies]
criterion = "0.5.1"
lazy_static = "1.5.0"
futures="0.3.30"
tokio = {version = "1.38.0", features = ["rt", "macros", "rt-multi-thread", "time"]}

[[bench]]
name = "benches"
harness = false
required-features = ["bench"]

[[example]]
name = "insert"
required-features = ["bench"]
