[package]
name = "cosmian_findex"
version = "7.0.0"
authors = [
    "Bruno Grieder <bruno.grieder@cosmian.com>",
    "Célia Corsin <celia.corsin@cosmian.com>",
    "Chloé Hébant <chloe.hebant@cosmian.com>",
    "Emmanuel Coste <emmanuel.coste@cosmian.com>",
    "Hatem Mnaouer <hatem.mnaouer@cosmian.com>",
    "Théophile Brézot <theophile.brezot@cosmian.com>",
]
categories = ["cryptography"]
edition = "2021"
keywords = ["SSE"]
license = "BUSL-1.1"
repository = "https://github.com/Cosmian/findex/"
description = "Symmetric Searchable Encryption"

[lib]
name = "cosmian_findex"
path = "src/lib.rs"

[features]
redis-mem = ["redis"]
sqlite-mem = ["async-sqlite"]
test-utils = ["tokio/rt-multi-thread"]
postgres-mem = [
    "tokio-postgres",
    "tokio/rt-multi-thread",
    "deadpool-postgres",
    "tokio-retry",
]

[dependencies]
aes = "0.8.4"
async-sqlite = { version = "0.5.0", optional = true }
deadpool-postgres = { version = "0.14.1", optional = true }
rand = "0.9.0"
rand_chacha = "0.9.0"
rand_core = "0.9.0"
redis = { version = "0.28.2", features = [
    "aio",
    "connection-manager",
    "tokio-comp",
], optional = true }
tiny-keccak = { version = "2.0.2", features = ["sha3"] }
tokio = { version = "1.44.0", optional = true }
tokio-postgres = { version = "0.7.13", optional = true, features = [
    "array-impls",
] }
tokio-retry = { version = "0.3.0", optional = true }
xts-mode = "0.5.1"
zeroize = { version = "1.8.1", features = ["derive"] }

[dev-dependencies]
criterion = "0.5.1"
futures = "0.3.31"
lazy_static = "1.5.0"
tokio = { version = "1.43.0", features = ["macros", "rt-multi-thread", "time"] }

[[bench]]
name = "benches"
harness = false
required-features = ["test-utils"]

[[example]]
name = "insert"
required-features = ["test-utils"]
