[package]
name = "findex-bis"
version = "0.1.0"
edition = "2021"

[features]
bench = []

[dependencies]
aes = "0.8.4"
cosmian_crypto_core = {git = "https://github.com/Cosmian/crypto_core.git", branch = "tbz/derive-clone-for-symkey", default-features = false, features = ["aes", "sha3"]}

[dev-dependencies]
futures = "0.3.30"
cosmian_crypto_core = {git = "https://github.com/Cosmian/crypto_core.git", branch = "tbz/derive-clone-for-symkey", default-features = false, features = ["aes", "sha3"]}
criterion = "0.5.1"
tokio = {version = "1.38.0", features = ["rt", "macros", "rt-multi-thread", "time"]}

[[bench]]
name = "benches"
harness = false
required-features = ["bench"]

[[example]]
name = "insert"
required-features = ["bench"]
