[package]
name = "cosmian_findex"
version = "5.0.1"
authors = [
  "Chloé Hébant <chloe.hebant@cosmian.com>",
  "Bruno Grieder <bruno.grieder@cosmian.com>",
  "Célia Corsin <celia.corsin@cosmian.com>",
  "Emmanuel Coste <emmanuel.coste@cosmian.com>",
  "Théophile Brézot <theophile.brezot@cosmian.com>",
]
categories = ["cosmian::crypto"]
edition = "2021"
keywords = ["SSE"]
license-file = "LICENSE.md"
repository = "https://github.com/Cosmian/findex/"
description = "Symmetric Searchable Encryption"

[lib]
crate-type = ["cdylib", "lib", "staticlib"]
name = "cosmian_findex"
path = "src/lib.rs"

[features]
in_memory = []

[dependencies]
# Once available in stable Rust (presumably 1.74), use std async fn in trait
# <https://rust-lang.github.io/rfcs/3185-static-async-fn-in-trait.html>
async-trait = "0.1"
base64 = "0.21.2"
cosmian_crypto_core = { version = "9.1.0", features = [
  "aes",
  "sha3",
  "ser",
], default-features = false }
# Once available in stable Rust, use `!` std primitive
# <https://doc.rust-lang.org/std/primitive.never.html>
never = "0.1"
rand = "0.8"
tiny-keccak = { version = "2.0.2", features = ["kmac", "sha3"] }
zeroize = "1.5"

[dev-dependencies]
actix-rt = "2.8"
criterion = { version = "0.5", features = [
  "html_reports",
  "async_futures",
], default_features = false }
futures = "0.3"
serde_json = "1.0"

[[bench]]
harness = false
name = "benches"
required-features = ["in_memory"]

[[test]]
name = "test_in_memory"
required-features = ["in_memory"]

[[test]]
name = "non_regression"
required-features = ["in_memory"]

[[example]]
name = "search"
required-features = ["in_memory"]

[[example]]
name = "upsert"
required-features = ["in_memory"]
