[package]
name = "findex-bis"
version = "0.1.0"
edition = "2021"

[dependencies]
aes = "0.8.4"
cosmian_crypto_core = {version = "9.4.0", default-features = false, features = ["aes", "sha3"]}

[dev-dependencies]
futures = "0.3.30"
