[package]
name = "cosmian_findex"
version = "6.0.0"
authors = [
  "Chloé Hébant <chloe.hebant@cosmian.com>",
  "Bruno Grieder <bruno.grieder@cosmian.com>",
  "Célia Corsin <celia.corsin@cosmian.com>",
  "Emmanuel Coste <emmanuel.coste@cosmian.com>",
  "Théophile Brézot <theophile.brezot@cosmian.com>",
]
categories = ["cosmian::crypto"]
edition = "2021"
keywords = ["SSE"]
license-file = "LICENSE.md"
repository = "https://github.com/Cosmian/findex/"
description = "Symmetric Searchable Encryption"

[lib]
crate-type = ["cdylib", "lib", "staticlib"]
name = "cosmian_findex"
path = "src/lib.rs"

[features]
in_memory = ["cosmian_crypto_core/ser"]
# Used to avoid compiling broken tests.
all_tests = ["in_memory"]

[dependencies]
base64 = "0.21.7"
cosmian_crypto_core = { git = "https://github.com/Cosmian/crypto_core.git", branch = "develop", default-features = false, features = [
  "aes",
  "sha3",
] }

# Once available in stable Rust, use `!` std primitive
# <https://doc.rust-lang.org/std/primitive.never.html>
never = "0.1.0"
tiny-keccak = { version = "2.0.2", features = ["kmac", "sha3"] }
tracing = "0.1"

[dev-dependencies]
actix-rt = "2.10.0"
criterion = "0.5.1"
futures = "0.3.30"
rand = "0.8.5"

[[bench]]
harness = false
name = "benches"
required-features = ["in_memory"]

# [[test]]
# name = "test_in_memory"
# required-features = ["all_tests"]

# [[test]]
# name = "non_regression"
# required-features = ["all_tests"]

[[example]]
name = "search"
required-features = ["all_tests"]

[[example]]
name = "upsert"
required-features = ["all_tests"]
