[package]
name = "cosmian-semantic-search"
version.workspace = true
authors.workspace = true
categories.workspace = true
edition.workspace = true
keywords.workspace = true
license.workspace = true
repository.workspace = true
description.workspace = true
readme = "README.md"

[lib]
name = "cosmian_semantic_search"
path = "src/lib.rs"
crate-type = ["lib", "cdylib"] # cdylib is required for Python bindings.

[[bench]]
name = "benches"
harness = false
required-features = ["test-utils"]

[[test]]
name = "integration_tests"
required-features = ["test-utils"]

[features]
default = ["test-utils"]
test-utils = ["cosmian_sse_memories/redis-mem", "cosmian_findex/test-utils"]

[dependencies]
cosmian_sse_memories = { path = "../memories", version = "8.0", features = ["postgres-mem"]}
cosmian_findex       = { path = "../findex", version = "8.0" }
rand = "0.9.2"
rand_distr = "0.5.1"
pyo3 = {version = "0.27"}
cosmian_crypto_core.workspace = true
tokio.workspace = true
zstd = { version = "0.13.3"}
clap = { version = "4.0.32", features = ["derive"] }
anyhow = "1.0.71"
serde_json = "1.0.102"
serde = "1.0.228"
# futures = "0.3.31"

[dev-dependencies]
criterion.workspace = true
futures = "0.3.31"
# tokio = { workspace = true, features = ["macros", "rt-multi-thread"] }

