[package]
name = "findex_in_memory"
version = "0.1.0"
edition = "2021"

[lib]
name = "cosmian_findex_in_memory"
path = "src/lib.rs"

[dependencies]
cosmian_findex = { path = ".." }
cosmian_crypto_core = "7.0.0"
rand = "0.8"

[dev-dependencies]
futures = "0.3"
