[package]
name = "cosmian_findex"
version = "7.2.0"
authors.workspace = true
categories.workspace = true
edition.workspace = true
keywords.workspace = true
license.workspace = true
repository.workspace = true
description.workspace = true
readme.workspace = true

[lib]
name = "cosmian_findex"
path = "src/lib.rs"

[features]
test-utils = ["tokio", "criterion", "rand", "rand_distr"]

[dependencies]
cosmian_crypto_core.workspace = true
aes = "0.8"
xts-mode = "0.5"

# Optional dependencies for testing and benchmarking
tokio = { workspace = true, features = [
    "rt-multi-thread",
    "macros",
], optional = true }
criterion = { workspace = true, optional = true }
rand = { workspace = true, optional = true }
rand_distr = { workspace = true, optional = true }

[dev-dependencies]
tokio = { workspace = true, features = ["macros", "rt-multi-thread"] }

[[bench]]
name = "benches"
harness = false
required-features = ["test-utils"]

[[example]]
name = "insert"
required-features = ["test-utils"]
