---
name: Benches
run-name: Benchmark on ${{ github.ref_name }} - ${{ github.sha }}

on: workflow_dispatch

jobs:
  bench:
    uses: Cosmian/reusable_workflows/.github/workflows/cargo-bench.yml@develop
    with:
      toolchain: 1.87.0
      features: test-utils,redis-mem,sqlite-mem,rust-mem,postgres-mem
      force: true
