---
name: Benches
run-name: Benchmark on ${{ github.ref_name }} - ${{ github.event.head_commit.message }}

on: workflow_dispatch

jobs:
  bench:
    uses: Cosmian/reusable_workflows/.github/workflows/cargo-bench.yml@develop
    with:
      toolchain: stable
      features: test-utils,redis-mem,sqlite-mem,rust-mem,postgres-mem
      force: true
