---
name: Benches
run-name: Benchmark - ${{ github.event.head_repository.name }}

on: workflow_dispatch

jobs:
  bench:
    uses: Cosmian/reusable_workflows/.github/workflows/cargo-bench.yml@develop
    with:
      toolchain: stable
      features: test-utils,redis-mem
      force: true
