---
name: Benches
run-name: Benchmark on ${{ github.ref_name }} - ${{ github.sha }}

on:
  push:
    branches: # it's useful to have an automated benchmark after each successful update
      - main
      - develop
  workflow_dispatch:

env:
  REDIS_HOST: "redis"
  POSTGRES_HOST: "postgres"

jobs:
  bench:
    uses: Cosmian/reusable_workflows/.github/workflows/cargo-bench.yml@fix/add_hosts_arguments
    with:
      toolchain: 1.87.0
      features: test-utils,redis-mem,sqlite-mem,postgres-mem
      force: true
      redis-host: "redis"
      postgres-host: "postgres"
