---
name: Benches

on: [workflow_dispatch, pull_request]

jobs:
  bench:
    uses: Cosmian/reusable_workflows/.github/workflows/cargo-bench.yml@develop
    with:
      toolchain: nightly-2022-10-28
      force: true
