---
name: Benches

on: workflow_dispatch

jobs:
  bench:
    uses: Cosmian/reusable_workflows/.github/workflows/cargo-bench.yml@develop
    with:
      toolchain: stable
      features: test-utils,postgres-mem,redis-mem,sqlite-mem,rust-mem
      force: true
