---
name: Benches on demand

# on: push
on: workflow_dispatch

jobs:
  bench:
    uses: Cosmian/reusable_workflows/.github/workflows/cargo-bench.yml@develop
    with:
      toolchain: nightly-2022-10-28
      force: true
