---
name: Benches

on: workflow_dispatch

jobs:
  bench:
    uses: Cosmian/reusable_workflows/.github/workflows/cargo-bench.yml@fix/bench_not_sgx2
    with:
      toolchain: stable
      features: test-utils,redis-mem,sqlite-mem,rust-mem
      force: true
