---
name: CI checks

on:
  workflow_call:
    inputs:
      toolchain:
        required: true
        type: string

jobs:
  cargo-lint:
    uses: Cosmian/reusable_workflows/.github/workflows/cargo-lint.yml@develop
    with:
      toolchain: ${{ inputs.toolchain }}
  cargo-fmt:
    uses: Cosmian/reusable_workflows/.github/workflows/cargo-fmt.yml@develop
    with:
      toolchain: nightly-2025-03-31
  cargo-audit:
    uses: Cosmian/reusable_workflows/.github/workflows/cargo-audit.yml@develop
    with:
      toolchain: ${{ inputs.toolchain }}
  cargo-machete:
    uses: Cosmian/reusable_workflows/.github/workflows/cargo-machete.yml@develop
    with:
      toolchain: ${{ inputs.toolchain }}
  cargo-doc:
    uses: Cosmian/reusable_workflows/.github/workflows/cargo-doc.yml@develop
    with:
      toolchain: ${{ inputs.toolchain }}
  cargo-semver:
    uses: Cosmian/reusable_workflows/.github/workflows/cargo-semver.yml@develop
    with:
      toolchain: ${{ inputs.toolchain }}
  cargo-publish-workspace:
    uses: Cosmian/reusable_workflows/.github/workflows/cargo-publish-workspace.yml@develop
    with:
      toolchain: ${{ inputs.toolchain }}
    secrets:
      token: ${{ secrets.CRATES_IO }}
