---
name: CI checks

on: push

jobs:
  cargo-lint:
    uses: Cosmian/reusable_workflows/.github/workflows/cargo-nursery.yml@feat/publish_workspace_fix
    with:
      toolchain: 1.85.0
  cargo-publish:
    needs:
      - cargo-lint
    uses: Cosmian/reusable_workflows/.github/workflows/cargo-publish.yml@feat/publish_workspace_fix
    if: startsWith(github.ref, 'refs/tags/')
    with:
      toolchain: 1.85.0
    secrets: inherit
  cleanup:
    needs:
      - cargo-lint
    uses: Cosmian/reusable_workflows/.github/workflows/cleanup_cache.yml@feat/publish_workspace_fix
    secrets: inherit
