---
name: CI checks

on: push

jobs:
  hack:
    runs-on: ubuntu-latest
    steps:
      - name: Check semver
        uses: obi1kenobi/cargo-semver-checks-action@v2
  cargo-lint:
    uses: Cosmian/reusable_workflows/.github/workflows/cargo-nursery.yml@develop
    with:
      toolchain: stable
  cargo-publish:
    needs:
      - cargo-lint
    uses: Cosmian/reusable_workflows/.github/workflows/cargo-publish.yml@develop
    if: startsWith(github.ref, 'refs/tags/')
    with:
      toolchain: stable
    secrets: inherit
  cleanup:
    needs:
      - cargo-lint
    uses: Cosmian/reusable_workflows/.github/workflows/cleanup_cache.yml@develop
    secrets: inherit
