---
name: CI checks

on: push

jobs:
  cargo-lint:
    uses: Cosmian/reusable_workflows/.github/workflows/cargo-nursery.yml@develop
    with:
      toolchain: 1.87.0
      workspace: true
    secrets:
      token: ${{ secrets.CRATES_IO }}
  cleanup:
    needs:
      - cargo-lint
    uses: Cosmian/reusable_workflows/.github/workflows/cleanup_cache.yml@develop
    secrets: inherit
