---
name: Features powerset checks

on: pull_request

jobs:
  hack:
    runs-on: ubuntu-latest
    steps:
      - name: Check storage
        run: df -h
      - uses: actions/checkout@v1
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
      - name: Install cargo-hack
        run: cargo install --locked cargo-hack || true
      - name: Test all feature combinations
        run: cargo hack test --feature-powerset --all-targets --clean-per-run
